### ISSUE TITLE
Hybopthiridae Ewing, 1929 and descendants

### ISSUE THREAD

**Issue by sjl197** [sfg-taxonpages/psocodea#1]
On your link to this family "Hybopthiridae".  [https://psocodea.speciesfile.org/otus/879047/overview]
This is a misspelling of "Hybophthiridae" (with extra "h"). I built in wikispecies with some key links 
(i.e. see: https://species.wikimedia.org/wiki/Hybophthiridae)

The original spelling of Ewing, 1929 is = Hybophthiridae
This original stem etc is a correct derivation of the type genus "[Hybophthirus] (https://species.wikimedia.org/wiki/Hybophthirus)"

The alternative spelling of "Hybopthiridae" [=sic] seems unjustified. Even if Ewing, 1929 had used it, then ICZN 35.4.1 would invoke need to 'be corrected' to reflect the spelling of the type genus (with extra "h"). The exception of prevailing usage would not apply as i find several authors give the 'original/correct' spelling, i.e. "Hybophthiridae"

Else, the supposed synonym stated as "*Hybophthirus orycteropodi* Enderlein, 1909" (see https://psocodea.speciesfile.org/otus/879048/overview) seems instead to have the original spelling as *Hybophthirus orycteropodis* Enderlein, 1909 (https://species.wikimedia.org/wiki/Template:Enderlein,_1909a). I see no justifiable reason why the final 'S' of the original spelling gets omitted by later authors, nor by [Psocodea Species File](https://psocodea.speciesfile.org/otus/879049/overview). Of course, it's fine to cite the misspelling, but please recognise it as that.

Finally in general, i added some links to several key papers to the wikispecies, including Enderlein, 1909 - where notably i'm also unclear how best to formulate that reference, it seems somewhere between a book and journal (https://species.wikimedia.org/wiki/Hybophthirus_notophallus)

**Comment by hhopkins77** [comment]
Stuart, thank you for your close attention to these entries and detailed assistance with the corrections. All should be corrected now. Please do not hesitate to be in touch with any other additions or corrections.
